name: myweb application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_VAR: value_from_env2
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_VAR
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build & Push Image
      run: |
        docker build -t chihjenhuang/myweb:v2 .
        docker push chihjenhuang/myweb:v2
