name: myweb application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: step-1 - checkout out
      uses: actions/checkout@v2
    - name: step-2 - docker login
      env:
        DOCKER_VAR: value_from_env2
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_VAR
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: step-3 - build & push myweb
      working-directory: myweb
      run: |
        docker build -t chihjenhuang/myweb:v3 .
        docker push chihjenhuang/myweb:v3
    - name: step-4 - build & push myweb2
      working-directory: myweb2
      run: |
        docker build -t chihjenhuang/myweb2:v1 .
        docker push chihjenhuang/myweb2:v1
